updated README and added test for  config/config.yml file
Signed-off-by: Toma Luca <toma.luca95@gmail.com>

diff --git a/bin/wtl-setup-test b/bin/wtl-setup-test
--- a/bin/wtl-setup-test
+++ b/bin/wtl-setup-test
@@ -73,4 +73,9 @@ then
   echo "Missing config/repositories.yml"
   exit 1
 fi
+if test ! -f config/config.yml
+then
+  echo "Missing config/config.yml"
+  exit 1
+fi
 echo "OK"
